version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: woice_postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    build: .
    container_name: woice_web
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 5; done; echo "Web ready"; tail -f /dev/null'
    volumes:
      - ".:/code"
    ports:
      - "8016:8016"
    depends_on:
      - postgres
    env_file: .env-docker