# Generated by Django 3.2.3 on 2021-05-20 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Invitees to private lobby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='user',
            field=models.ForeignKey(help_text='Creator of the lobby', on_delete=django.db.models.deletion.CASCADE, related_name='created_lobbies', to=settings.AUTH_USER_MODEL),
        ),
    ]
